name: Build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
      env:
        CI: true
    - name: Lint
      run: yarn lint
      env:
        CI: true
    - name: Build
      run: yarn build
      env:
        CI: true
    - name: Run tests
      run: yarn test --coverage
      env:
        CI: true
