name: Publish on NPM
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Check version changes
      uses: EndBug/version-check@v1.0.0
      id: versioncheck
    - name: Use Node.js ${{ matrix.node-version }}
      if: steps.versioncheck.outputs.changed == 'true'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      if: steps.versioncheck.outputs.changed == 'true'
      run: yarn install
      env:
        CI: true
    - name: Lint
      if: steps.versioncheck.outputs.changed == 'true'
      run: yarn lint
      env:
        CI: true
    - name: Build
      if: steps.versioncheck.outputs.changed == 'true'
      run: yarn build
      env:
        CI: true
    - name: Run tests
      if: steps.versioncheck.outputs.changed == 'true'
      run: yarn test --coverage
      env:
        CI: true
    - name: Upload artifacts
      if: steps.versioncheck.outputs.changed == 'true'
      uses: actions/upload-artifact@master
      with:
        name: package
        path: dist/
    - name: Version update detected
      if: steps.versioncheck.outputs.changed == 'true'
      run: 'echo "Version change! -> ${{ steps.versioncheck.outputs.type }}"'
    - name: Set up Node.js for NPM
      if: steps.versioncheck.outputs.changed == 'true'
      uses: actions/setup-node@v1.2.0
      with:
        registry-url: 'https://registry.npmjs.org'
    - name: Publish package to NPM
      if: steps.versioncheck.outputs.changed == 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
