name: Publish on NPM
on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Publish

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Check version changes
      uses: EndBug/version-check@v1.0.0
      id: check
      with:
        file-name: package.json
        diff-search: true
    - name: Use Node.js ${{ matrix.node-version }}
      # if: steps.check.outputs.changed == 'true'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      # if: steps.check.outputs.changed == 'true'
      run: npm ci
    - name: Lint
      # if: steps.check.outputs.changed == 'true'
      run: npm run lint
    - name: Build
      # if: steps.check.outputs.changed == 'true'
      run: npm run build
    - name: Run tests
      # if: steps.check.outputs.changed == 'true'
      run: npm run test
 #   - name: Set up Node.js for NPM
 #     # if: steps.check.outputs.changed == 'true'
 #     uses: actions/setup-node@v1.2.0
 #     env:
 #       NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
 #     with:
 #       registry-url: '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'
    - name: Publish package to NPM
      # if: steps.check.outputs.changed == 'true'
      run: |
        echo //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN > .npmrc
        npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
        npm whoami
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

