name: Publish on NPM
on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Publish

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Check version changes
      uses: EndBug/version-check@v1.0.0
      id: check
      with:
        file-name: package.json
        diff-search: true
    - name: Use Node.js ${{ matrix.node-version }}
      # if: steps.check.outputs.changed == 'true'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      # if: steps.check.outputs.changed == 'true'
      run: npm ci
    - name: Lint
      # if: steps.check.outputs.changed == 'true'
      run: npm run lint
    - name: Build
      # if: steps.check.outputs.changed == 'true'
      run: npm run build
    - name: Run tests
      # if: steps.check.outputs.changed == 'true'
      run: npm run test
    - name: Publish package to NPM
      if: steps.check.outputs.changed == 'true'
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: Publish package to GPR
#      if: steps.check.outputs.changed == 'true'
      run: |
        cat package.json
        npm config set registry https://npm.pkg.github.com/
        npm config set //npm.pkg.github.com/:_authToken=$GITHUB_AUTH_TOKEN
        npm publish
      env:
        GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}

        # sed 's/@sergeyzwezdin/@pixel-grid/g' < package.json > package.json
